### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by sumarouno** [wilberforce/lcd-pcf8574#6]
chip@chip:~/node_modules$ node -v
v4.5.0

chip@chip:~/node_modules$ npm -v
2.15.9

**Comment by wilberforce** [comment]
@sumarouno 
Sorry - you have not provided enough information for me to help.

If you paste the output of `npm install` for the module - that might provide some clues.

**Comment by MarcosRZ** [comment]
It seems that there's a problem with i2c package. I can share my npm-debug.log, but it's 500+ lines long, and there's no "attach file" option here. Please, try to make a clean install and I guess you'll get the same error. Thanks.

**Comment by wga22** [comment]
I am having a similar issue that I cannot install due to i2c.

`i2c.target.mk:90: recipe for target 'Release/obj.target/i2c/src/i2c.o' failed
make: *** [Release/obj.target/i2c/src/i2c.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/i2c-lcd/node_modules/i2c/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.50+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/i2c-lcd/node_modules/i2c
gyp ERR! node -v v7.6.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
/usr/local/lib
└── (empty)

npm ERR! Linux 4.4.50+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "i2c-lcd"
npm ERR! node v7.6.0
`

**Comment by kevincastejon** [comment]
If you have trouble installing/using this repo try this new one :
https://github.com/kevincastejon/js-raspberrypi-liquid-crystal
It uses the updated 'i2c-bus' module instead of the old 'i2c' one and its API is the same as the Arduino LiquidCrystal library.
